AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/*"
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
